import tkinter as tk
import logic
import charts

root = tk.Tk()
root.geometry('400x400')
root.resizable(False, False)
root.configure(bg='black')
text_result = tk.Text(root, height=3, width=22, font=('Arial', 24))
text_result.grid(columnspan=5)
btn_1 = tk.Button(root, text='1', command=lambda: logic.add_to_calculation(1), width=8, font=('Arial', 14), bg='red')
btn_1.grid(row=2, column=1)
btn_2 = tk.Button(root, text='2', command=lambda: logic.add_to_calculation(2), width=8, font=('Arial', 14), bg='red')
btn_2.grid(row=2, column=2)
btn_3 = tk.Button(root, text='3', command=lambda: logic.add_to_calculation(3), width=8, font=('Arial', 14), bg='red')
btn_3.grid(row=2, column=3)
btn_4 = tk.Button(root, text='4', command=lambda: logic.add_to_calculation(4), width=8, font=('Arial', 14), bg='red')
btn_4.grid(row=3, column=1)
btn_5 = tk.Button(root, text='5', command=lambda: logic.add_to_calculation(5), width=8, font=('Arial', 14), bg='red')
btn_5.grid(row=3, column=2)
btn_6 = tk.Button(root, text='6', command=lambda: logic.add_to_calculation(6), width=8, font=('Arial', 14), bg='red')
btn_6.grid(row=3, column=3)
btn_7 = tk.Button(root, text='7', command=lambda: logic.add_to_calculation(7), width=8, font=('Arial', 14), bg='red')
btn_7.grid(row=4, column=1)
btn_8 = tk.Button(root, text='8', command=lambda: logic.add_to_calculation(8), width=8, font=('Arial', 14), bg='red')
btn_8.grid(row=4, column=2)
btn_9 = tk.Button(root, text='9', command=lambda: logic.add_to_calculation(9), width=8, font=('Arial', 14), bg='red')
btn_9.grid(row=4, column=3)
btn_0 = tk.Button(root, text='0', command=lambda: logic.add_to_calculation(0), width=8, font=('Arial', 14), bg='red')
btn_0.grid(row=5, column=2)
btn_plus = tk.Button(root, text='+', command=lambda: logic.add_to_calculation('+'), width=8, font=('Arial', 14), bg='red')
btn_plus.grid(row=2, column=4)
btn_minus = tk.Button(root, text='-', command=lambda: logic.add_to_calculation('-'), width=8, font=('Arial', 14), bg='red')
btn_minus.grid(row=3, column=4)
btn_multi = tk.Button(root, text='*', command=lambda: logic.add_to_calculation('*'), width=8, font=('Arial', 14), bg='red')
btn_multi.grid(row=4, column=4)
btn_div = tk.Button(root, text='/', command=lambda: logic.add_to_calculation('/'), width=8, font=('Arial', 14), bg='red')
btn_div.grid(row=5, column=4)
btn_open = tk.Button(root, text='(', command=lambda: logic.add_to_calculation('('), width=8, font=('Arial', 14), bg='red')
btn_open.grid(row=5, column=1)
btn_close = tk.Button(root, text=')', command=lambda: logic.add_to_calculation(')'), width=8, font=('Arial', 14), bg='red')
btn_close.grid(row=5, column=3)
btn_sin = tk.Button(root, text='sin()', command=logic.sin, width=8, font=('Arial', 14), bg='red')
btn_sin.grid(row=6, column=1)
btn_cos = tk.Button(root, text='cos()', command=logic.cos, width=8, font=('Arial', 14), bg='red')
btn_cos.grid(row=6, column=2)
btn_tan = tk.Button(root, text='tan()', command=logic.tan, width=8, font=('Arial', 14), bg='red')
btn_tan.grid(row=6, column=3)
btn_ctg = tk.Button(root, text='ctg()', command=logic.ctg, width=8, font=('Arial', 14), bg='red')
btn_ctg.grid(row=6, column=4)
btn_draw_sin = tk.Button(root, text='draw_sin', command=charts.sin.draw_trig, width=8, font=('Arial', 14), bg='red')
btn_draw_sin.grid(row=7, column=1)
btn_draw_cos = tk.Button(root, text='draw_cos', command=charts.cos.draw_trig, width=8, font=('Arial', 14), bg='red')
btn_draw_cos.grid(row=7, column=2)
btn_draw_tan = tk.Button(root, text='draw_tan', command=charts.tan.draw_trig, width=8, font=('Arial', 14), bg='red')
btn_draw_tan.grid(row=7, column=3)
btn_equals = tk.Button(root, text='=', command=logic.evaluate_calculation, width=11, font=('Arial', 14), bg='red')
btn_equals.grid(row=8, column=3, columnspan=2)
btn_clear = tk.Button(root, text='C', command=logic.clear_field, width=11, font=('Arial', 14), bg='red')
btn_clear.grid(row=8, column=1, columnspan=2)
root.mainloop()
